Repository 9oormthon-univ/2025_SEASONTHON_TEAM_54_FE, pull requests merged in 2025-09, with the labels that each got.

#18 [feat/#17] core component
  app/src/main/java/org/ssg_tab/core/designsystem/component/SsgTabButton.kt
  app/src/main/java/org/ssg_tab/core/designsystem/component/SsgTabMainChip.kt
  app/src/main/java/org/ssg_tab/core/designsystem/component/SsgTabTextField.kt
  app/src/main/java/org/ssg_tab/core/designsystem/component/SsgTabTopBar.kt
  app/src/main/java/org/ssg_tab/core/designsystem/theme/Color.kt
  app/src/main/java/org/ssg_tab/core/designsystem/theme/Type.kt
  app/src/main/res/drawable/ic_bottomnav_home_off.xml
  app/src/main/res/drawable/ic_bottomnav_home_on.xml
  app/src/main/res/drawable/ic_bottomnav_study_off.xml
  app/src/main/res/drawable/ic_bottomnav_study_on.xml
  app/src/main/res/drawable/ic_category_off.xml
  app/src/main/res/drawable/ic_category_on.xml
  app/src/main/res/drawable/ic_core_back.xml
  app/src/main/res/drawable/ic_core_close.xml
  app/src/main/res/drawable/ic_core_save.xml
  app/src/main/res/drawable/ic_core_search.xml
  app/src/main/res/drawable/ic_home_alarm_off.xml
  app/src/main/res/drawable/ic_home_alarm_on.xml
  app/src/main/res/drawable/ic_home_like_o.xml
  app/src/main/res/drawable/ic_home_like_off.xml
  app/src/main/res/drawable/ic_home_share.xml
  app/src/main/res/drawable/ic_login_invalid.xml
  app/src/main/res/drawable/ic_login_valid.xml
  app/src/main/res/drawable/ic_profile_camera.xml
Labels: feature ✨, 주완🐹

#26 [feat/#25] study view 작업
  app/src/main/java/org/ssg_tab/core/designsystem/component/SsgTabTopBar.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/GuideScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/QuizScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/AnimatedBottomSheet.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/GuideMyCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/GuideRankCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/LearningStatsCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/ProgressSummaryCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/navigation/GuideNavigation.kt
  app/src/main/res/drawable/ic_study_arrow_right.xml
  app/src/main/res/drawable/ic_study_basic.xml
  app/src/main/res/drawable/ic_study_lv1.xml
  app/src/main/res/drawable/ic_study_lv2.xml
  app/src/main/res/drawable/ic_study_lv3.xml
  app/src/main/res/drawable/ic_study_lv4.xml
  app/src/main/res/drawable/ic_study_my_profile.xml
  app/src/main/res/drawable/ic_study_tob.xml
Labels: feature ✨, 주완🐹

#41 [feat/#37] Quiz api 연동
  app/src/main/java/org/ssg_tab/data/di/DataSourceModule.kt
  app/src/main/java/org/ssg_tab/data/di/NetworkModule.kt
  app/src/main/java/org/ssg_tab/data/di/RepositoryModule.kt
  app/src/main/java/org/ssg_tab/data/dto/response/BaseResponse.kt
  app/src/main/java/org/ssg_tab/data/dto/response/quiz/QuizResponseDto.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/QuizDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/QuizDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/quiz/QuizRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/service/QuizService.kt
  app/src/main/java/org/ssg_tab/domain/model/entity/QuizEntity.kt
  app/src/main/java/org/ssg_tab/domain/repository/quiz/QuizRepository.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/GuideScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/QuizScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/AnimatedBottomSheet.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/model/QuizViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/state/QuizContract.kt
Labels: feature ✨, 주완🐹

#43 Feat/#40 user information view
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/SelectAgeHomeScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/SelectCategoryScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/SelectJobScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/component/InterestChip.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/component/SelectableChip.kt
  app/src/main/res/drawable/ic_progress_bar.xml
  app/src/main/res/drawable/ic_progress_bar_2.xml
  app/src/main/res/drawable/ic_progress_bar_3.xml
Labels: feature ✨, 영원🐰

#48 [feat/#47] home feed api 연동
  app/src/main/java/org/ssg_tab/data/di/DataSourceModule.kt
  app/src/main/java/org/ssg_tab/data/di/NetworkModule.kt
  app/src/main/java/org/ssg_tab/data/di/RepositoryModule.kt
  app/src/main/java/org/ssg_tab/data/dto/response/base/BaseResponse.kt
  app/src/main/java/org/ssg_tab/data/dto/response/home/HomeFeedResponseDto.kt
  app/src/main/java/org/ssg_tab/data/dto/response/quiz/QuizResponseDto.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/home/HomeFeedDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/quiz/QuizDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/home/HomeFeedDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/quiz/QuizDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/home/HomeFeedRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/quiz/QuizRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/service/home/HomeFeedService.kt
  app/src/main/java/org/ssg_tab/data/service/quiz/QuizService.kt
  app/src/main/java/org/ssg_tab/domain/model/entity/home/HomeFeedEntity.kt
  app/src/main/java/org/ssg_tab/domain/model/entity/quiz/QuizEntity.kt
  app/src/main/java/org/ssg_tab/domain/repository/home/HomeFeedRepository.kt
  app/src/main/java/org/ssg_tab/domain/repository/quiz/QuizRepository.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/QuizScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/model/QuizViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/state/QuizContract.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/model/HomeViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/state/HomeContract.kt
Labels: feature ✨, 주완🐹

#57 feat/#56: 토큰 관련
  app/build.gradle.kts
  app/src/main/java/org/ssg_tab/core/network/TokenManager.kt
  app/src/main/java/org/ssg_tab/data/di/NetworkModule.kt
  app/src/main/java/org/ssg_tab/data/remote/AuthInterceptor.kt
  app/src/main/java/org/ssg_tab/presentation/ui/login/model/LoginViewmodel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/login/navigation/LoginNavigation.kt
  gradle/libs.versions.toml
Labels: feature ✨, 영원🐰

#58 feat/#53: 관심사 선택 이미지 추가
  app/src/main/ic_category_job-playstore.png
  app/src/main/ic_category_job22-playstore.png
  app/src/main/java/org/ssg_tab/presentation/ui/mypage/SetInterestingScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/mypage/component/InterestChip.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/SelectCategoryScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/userinformation/component/InterestChip.kt
  app/src/main/res/drawable/ic_category_cryptocurrency.png
  app/src/main/res/drawable/ic_category_eco.png
  app/src/main/res/drawable/ic_category_fianace.png
  app/src/main/res/drawable/ic_category_for.png
  app/src/main/res/drawable/ic_category_fund.png
  app/src/main/res/drawable/ic_category_job.png
  app/src/main/res/drawable/ic_category_real.png
  app/src/main/res/drawable/ic_category_stock.png
  app/src/main/res/drawable/ic_category_sub.png
Labels: feature ✨, 영원🐰

#62 [mod/#60] home token (조회,좋아요) API 연동
  app/src/main/java/org/ssg_tab/data/dto/request/home/HomeLikeRequestDto.kt
  app/src/main/java/org/ssg_tab/data/dto/response/home/HomeFeedResponseDto.kt
  app/src/main/java/org/ssg_tab/data/dto/response/home/HomeLikeResponse.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/home/HomeLikeDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/home/HomeFeedDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/home/HomeLikeDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/home/HomeFeedRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/home/HomeLikeRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/service/home/HomeFeedService.kt
  app/src/main/java/org/ssg_tab/data/service/home/HomeLikeService.kt
  app/src/main/java/org/ssg_tab/domain/model/entity/home/HomeFeedEntity.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeActionButton.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeMainForm.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/model/HomeViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/state/HomeContract.kt
  app/src/main/res/drawable/ic_home_like_on.xml
Labels: mod 🎉, 주완🐹

#66 [feat/#63] storage api
  app/src/main/java/org/ssg_tab/data/di/DataSourceModule.kt
  app/src/main/java/org/ssg_tab/data/di/NetworkModule.kt
  app/src/main/java/org/ssg_tab/data/di/RepositoryModule.kt
  app/src/main/java/org/ssg_tab/data/dto/response/storage/StorageResponseDto.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/storage/StorageDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/storage/StorageDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/storage/StorageRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/service/storage/StorageService.kt
  app/src/main/java/org/ssg_tab/domain/model/entity/storage/StorageEntity.kt
  app/src/main/java/org/ssg_tab/domain/repository/storage/StorageRepository.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/StorageScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/StorageViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/navigation/StorageNavigation.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/state/StorageContract.kt
Labels: feature ✨, 주완🐹

#68 [feat/#67] study data api
  app/src/main/java/org/ssg_tab/data/di/DataSourceModule.kt
  app/src/main/java/org/ssg_tab/data/di/NetworkModule.kt
  app/src/main/java/org/ssg_tab/data/di/RepositoryModule.kt
  app/src/main/java/org/ssg_tab/data/dto/response/study/StudyResponseDto.kt
  app/src/main/java/org/ssg_tab/data/remote/datasource/study/StudyDataSource.kt
  app/src/main/java/org/ssg_tab/data/remote/datasourceImpl/study/StudyDataSourceImpl.kt
  app/src/main/java/org/ssg_tab/data/repositoryimpl/study/StudyRepositoryImpl.kt
  app/src/main/java/org/ssg_tab/data/service/study/StudyService.kt
  app/src/main/java/org/ssg_tab/domain/repository/study/StudyRepository.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/GuideScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/GuideMyCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/model/GuideViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/navigation/GuideNavigation.kt
  app/src/main/java/org/ssg_tab/presentation/ui/guide/state/GuideContract.kt
Labels: feature ✨, 주완🐹

#74 [mod/#73] UI 및 동작 디테일
  app/src/main/java/org/ssg_tab/presentation/ui/guide/component/GuideRankCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeActionButton.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeMainForm.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeMockComponent.kt
  app/src/main/java/org/ssg_tab/presentation/ui/home/component/HomeTopBar.kt
  app/src/main/java/org/ssg_tab/presentation/ui/mypage/MypageScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/mypage/component/UserProfileCard.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/StorageScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/StorageViewModel.kt
  app/src/main/java/org/ssg_tab/presentation/ui/storage/component/StorageTabButton.kt
  app/src/main/res/drawable/ic_like_re.xml
  app/src/main/res/drawable/img_logo.png
Labels: mod 🎉, 주완🐹

#77 [feat/#76] 애니메이션 튜토리얼
  app/build.gradle.kts
  app/src/main/java/org/ssg_tab/presentation/ui/login/LoginScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/login/TutorialScreen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/login/component/Tutorial2Screen.kt
  app/src/main/java/org/ssg_tab/presentation/ui/login/component/Tutorial3Screen.kt
  app/src/main/res/drawable/ic_login_logo.png
  app/src/main/res/drawable/ic_logo_text.png
  app/src/main/res/drawable/img_kakao.png
Labels: feature ✨, 주완🐹
